# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/colonel_dotto',
                'doc_host': 'https://TesfaAsmara.github.io',
                'git_url': 'https://github.com/TesfaAsmara/colonel_dotto',
                'lib_path': 'colonel_dotto'},
  'syms': {'colonel_dotto.core': {'colonel_dotto.core.foo': ('core.html#foo', 'colonel_dotto/core.py')}}}